# Generated by Django 6.0.2 on 2026-02-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'branch')},
        ),
    ]
