# Generated by Django 6.0.3 on 2026-03-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid'), ('CANCELLED', 'Cancelled'), ('WAITER PAID', 'Waiter Paid')], default='PENDING', max_length=15),
        ),
    ]
