# Generated by Django 6.0.3 on 2026-03-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_alter_invoice_payment_status'),
        ('api', '0080_alter_user_options_alter_invoice_payment_status_and_more'),
    ]

    operations = [
    ]
