# Generated by Django 6.0.3 on 2026-03-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_branch_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='is_active',
        ),
    ]
