# Generated by Django 6.0.3 on 2026-03-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_remove_branch_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together=set(),
        ),
    ]
