# Generated by Django 6.0.3 on 2026-03-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_alter_productcategory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together=set(),
        ),
    ]
