# Generated by Django 6.0.3 on 2026-03-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_alter_productcategory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('branch', 'name')},
        ),
    ]
